language: java


jdk:
  - oraclejdk8

  

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      file: 
          - MSantarsiere/pluginForLinux/pom.xml
      repo: MSantarsiere/pluginForLinux
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
        
      file: 
          - MSantarsiere/pluginForLinux/pom.xml
      repo: MSantarsiere/pluginForLinux
      tags: true
      jdk: oraclejdk8